package fr.core.error;

/*
 * Copyright 2015-2017 Emmanuel ZIDEL-CAUFFET
 *
 * This class is used in a project designed by some Ecole Centrale de Lille students.
 * This program is distributed in the hope that it will be useful.
 * 
 * It is a free code: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either Version 3 of the License.
 *
 * However the source code is distributed without any warranty
 * See the GNU General Public License for more details.
 *
 */


/** 
 * This interface is used to process an error returned by a NodeJS server or generated by a function in the JAR
 * @author Zidmann (Emmanuel ZIDEL-CAUFFET)
 * @version 1.1.0
 */

public interface ErrorInterface
{
	/**
	 * Identification number of the error
	 */
	String	code 	= "0"; 

	/**
	 * Text message of the error
	 */
	String	message = null; 

	/**
	 * Details of the error
	 */
	String	stack	= null; 

	/**
	 * Status of the error
	 */
	int 	status	= 404; 
}
